#Lines of code generated by ChatGPT will have [ChatGPT] comment next to it
#Blocks of code will have a '[ChatGPT] v' comment on the first line and '[ChatGPT] ^' comment on the last line, meaning everything in-between is generated

import sqlite3
from datetime import datetime
import matplotlib.pyplot as plt  

##PROGRAM MENU: Allow the user to choose some actions

#1 - Calculate BMI and category (overweight, underweight, etc.)
#2 - Displays BMI history 
#3-  Generate suggested meal plan
#4 - Update profile
#X - Log Out
#RESET - Wipes all data

##DATABASE SYSTEM
#The program uses a database with two tables

 #bmiHelper_USERS: This table stores individual user profiles (primary_id, name, password)
 #bmiHelper_RECORDS: This table stores personal info for each user (primary_id, user_id, date, age, height, weight, BMI)
 
   ##primary_id is used as the primary key
   ##user_id is used as the foreign key
 
##ASSUMPTIONS
#We will assume users enter the appropriate values when asked to 
##

# CONNECTING TO TABLES // code from Python SQLite – Create Table (edited with our variables)
print("Welcome to BMIHelper.")
# connection object        
connect_db = sqlite3.connect('bmi_Helper_v4.db')
# cursor object
cur = connect_db.cursor()
# creating USERS table
cur.execute("""CREATE TABLE IF NOT EXISTS bmiHelper_USERS(
primary_id INTEGER PRIMARY KEY AUTOINCREMENT, 
name TEXT NOT NULL,
password TEXT NOT NULL
)"""

)
# creating RECORDS table
cur.execute("""CREATE TABLE IF NOT EXISTS bmiHelper_RECORDS(
primary_id INTEGER PRIMARY KEY AUTOINCREMENT, 
user_id INTEGER NOT NULL,
date DATETIME NOT NULL, 
age INTEGER, 
height DECIMAL,
weight DECIMAL,
BMI DECIMAL,
classification TEXT,
gender TEXT,
FOREIGN KEY (user_id) REFERENCES bmiHelper_USERS (primary_id)
)"""
)

print("LOADING...")

current_user = '' 

# checks how many users are registered
cur.execute("""
   SELECT COUNT(*)
   FROM bmiHelper_USERS;
   """)
row_tuple = cur.fetchone()
rows = row_tuple[0]

# if there are no users yet, asks user to create a profile
if rows == 0:
 print("There is no data to load. Creating new profile...")
 current_user = input("Please enter your username: ")
 password = input("Please create a password: ")
 age = input("Enter your age: ")
 height = input("Enter your current height in cm: ")
 weight = input("Enter your current weight in kg: ")
 # allows user to choose their gender (will be used for food plan)
 looping = True
 while (looping == True):
  g_option = input("""
  How do you identify?
  
  M - Male
  F - Female
  X - Gender non-conforming
  
  """)
  gender = ""
  if g_option == "M":
   gender = "Male"
   looping = False
  elif g_option == "F":
   gender = "Female"
   looping = False
  elif g_option == "X":
   gender = "Gender non-conforming"
   looping = False
  else:
   print("Invalid input, please try again")
   looping = True
 
 # adds a new profile into USERS table
 cur.execute("""
 INSERT INTO bmiHelper_USERS(name, password) 
 VALUES(?,?)
 """, (current_user, password)) # borrowed from ChatGPT
 user_id = cur.lastrowid
 # records the profile data
 timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S') 
 cur.execute("""
 INSERT INTO bmiHelper_RECORDS(user_id, date, age, height, weight, gender)
 VALUES(?,?,?,?,?,?)
 """, (user_id, timestamp, age, height, weight, gender))
 print("A profile for " + current_user + " [ID: " + str(user_id) + "] has been created.")
 connect_db.commit()

# if there are registered users, asks user to log in or sign up
else:
    print("Data successfully retrieved.")
    msg = """
    Press A to sign in
    Press B to create a new account
    
    """
    while True:
     option = input(msg)
     if option == "A":
         while True:
             current_user = input("Please enter your username: ")
             # [ChatGPT] v
             query_name = ("SELECT * FROM bmiHelper_Users WHERE name = ?") 
             cur.execute(query_name, (current_user,)) 
             results = cur.fetchall() 
             # [ChatGPT] ^
             if results:
                 print("User found")
                 break
             else:
                 print("User not found, please try again.")
                 continue 
             break
         # gives you 3 attempts to enter the password    
         attempts_left = 2
         while True:
             user_PW = input("Please enter your password: ")
             query_PW = ("SELECT * FROM bmiHelper_Users WHERE password = ?")
             cur.execute(query_PW, (user_PW,))
             results = cur.fetchall()
             if results:
                 print("Successfully logged in!")
                 break
             elif not results and attempts_left > 0:
                 print("Incorrect password, please try again")
                 attempts_left = attempts_left - 1
                 print("Attempts left: " + str(attempts_left + 1))
                 continue
             elif not results and attempts_left == 0:
                 print("FORCE PROGRAM QUIT")
                 connect_db.close()
                 quit()
             break
                 
     elif option == "B":
      while True:
          current_user = input("Please enter your username: ")
          # check if this username has already been used
          query_name = ("SELECT * FROM bmiHelper_Users WHERE name = ?") 
          cur.execute(query_name, (current_user,)) 
          results = cur.fetchall() 
          if not results: 
           password = input("Please create a password: ")
           age = input("Enter your age: ")
           height = input("Enter your current height in cm: ")
           weight = input("Enter your current weight in kg: ")
           # allows user to choose their gender (will be used for food plan)
           looping = True
           while (looping == True):
            g_option = input("""
            How do you identify?
            
            M - Male
            F - Female
            X - Gender non-conforming
            
            """)
            gender = ""
            if g_option == "M":
             gender = "Male"
             looping = False
            elif g_option == "F":
             gender = "Female"
             looping = False
            elif g_option == "X":
             gender = "Gender non-conforming"
             looping = False
            else:
             print("Invalid input, please try again")
             looping = True
           
           # adds a new profile into USERS table
           cur.execute("""
           INSERT INTO bmiHelper_USERS(name, password) 
           VALUES(?,?)
           """, (current_user, password)) # [CHATGPT]
           user_id = cur.lastrowid
           # records the profile data
           timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S') 
           cur.execute("""
           INSERT INTO bmiHelper_RECORDS(user_id, date, age, height, weight, gender)
           VALUES(?,?,?,?,?,?)
           """, (user_id, timestamp, age, height, weight, gender))
           print("A profile for " + current_user + " [ID: " + str(user_id) + "] has been created.")
           connect_db.commit()
           break
          else:
           print("This username has already been taken. Please try again.")
           continue
         
     else:
         print("Invalid input, please try again")
         continue
     break

# MENU 
msg = """

1 - Calculate BMI and category (overweight, underweight, etc.)
2 - Displays BMI history 
3- Generate suggested meal plan
4 - Edit profile
X - Exit the program

"""
print("Hello, " + current_user)
print(msg)

# Gets User ID by retrieving a value from a tuple
cur.execute("SELECT primary_id FROM bmiHelper_USERS WHERE name = ?", (current_user,))
userID = cur.fetchone()[0]

option = 'PLACEHOLDER'
while option != 'X':
   option = input("[MAIN MENU] Choose an action: ") 
   #empty lists for displaying data for graphing purposes
   bmi_values = []
   weights = []
   dates = []
   classifications = []
   
   if option == "1": # CALCULATE BMI AND CATEGORY
    while True:
     #asks if user would like to use their current weight/height, or if they would like to update it
     option = input("Would you like to update your weight or height? Y/N")
     if option == "Y":
      # user updates their weight and height, which gets added to their profile record
      weight = float(input("Enter your new weight in kg: "))
      raw_height = float(input("Enter your new height in cm: "))
      break
      
     elif option == "N":
      # Retrieves the user's last recorded weight from the database, using the LIMIT clause
      cur.execute("""
      SELECT height, weight FROM bmiHelper_RECORDS
      WHERE user_id = ?
      ORDER BY date DESC
      LIMIT 1
      """, (userID,))
      result = cur.fetchone()
      raw_height, weight = result
      print("Last recorded weight: " + str(weight) + " kg")
      print("Last recorded height: " + str(raw_height) + " cm")
      break
      
     else:
      print("Invalid input, please try again")
      continue
 
    # Retrieve's the user's age and gender from previous records
    cur.execute("""
    SELECT age, gender, primary_id FROM bmiHelper_RECORDS
    WHERE user_id = ?
    ORDER BY date DESC
    LIMIT 1
    """, (userID,))
    result = cur.fetchone()
    age, gender, record_id = result
  
    # Calculate the BMI using the user's weight and previously stored height
    height = raw_height / 100 
    bmi = weight / (height ** 2)
       
    # Classify the BMI into categories based on standard ranges
    if bmi < 18.5:
       classification = "Underweight"
    elif 18.5 <= bmi < 24.9:
       classification = "Normal weight"
    elif 25 <= bmi < 29.9:
       classification = "Overweight"
    else:
       classification = "Obese"
    
    print("Your BMI is " + str(bmi) + ". You are classified as " + classification + ".")
       
    # Enters a new record with the newly calculated BMI
    timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    cur.execute("""
    INSERT INTO bmiHelper_RECORDS(user_id, date, age, height, weight, BMI, gender, classification)
    VALUES(?,?,?,?,?,?,?,?)
    """, (userID, timestamp, age, raw_height, weight, bmi, gender, classification))  
    connect_db.commit()
      
   
   elif option == "2": # DISPLAY BMI HISTORY
     # Retrieves the last calculated BMI - if it doesn't exist, returns None
     cur.execute("""
     SELECT BMI FROM bmiHelper_RECORDS
     WHERE user_id = ?
     ORDER BY date DESC
     LIMIT 1
     """, (userID,))
     result_value = cur.fetchone()[0]

     # Check if any BMI values were calculated before displaying the history
     if result_value is not None:
         dates.clear()
         bmi_values.clear()
         weights.clear()
         classifications.clear()
         # gets the user's weight, bmi, and bmi classification
         cur.execute("""
         SELECT date, BMI, weight, classification FROM bmiHelper_RECORDS 
         WHERE user_id = ? AND BMI NOT NULL
         ORDER BY date
         """, (userID,)) 
         # gets the user's BMI and weight history and classification for graphing
         # [ChatGPT] v
         all_records = cur.fetchall()
         print(all_records)
   
         # adds values to lists 
         for record in all_records:
          dates.append(record[0])  # Date
          bmi_values.append(record[1])  # BMI
          weights.append(record[2])  # Weight 
          classifications.append(record[3]) 
         # [ChatGPT] ^
          
         # Import libraries for plotting the bar graph (if desired)
         # This section would likely use libraries like matplotlib.pyplot
         # We'll skip the specific implementation here for simplicity.
 
         # Create a figure for the bar graph with appropriate dimensions
         plt.figure(figsize=(10, 5))
 
         # Define the width of each bar in the graph
         bar_width = 0.3
 
         # Create a list of positions for the bars based on the number of entries
         bar_positions = range(len(dates))
 
         # Generate bars representing the BMI values for each date
         plt.bar(bar_positions, bmi_values, width=bar_width, label='BMI', color='lightblue')
 
         # Add annotations to each bar displaying the classification and BMI value
         # [ChatGPT] v
         for i, (bmi, classification) in enumerate(zip(bmi_values, classifications)):
             # Position the annotation text above the bar with slight adjustment
             plt.text(i, bmi + 0.1, f'{classification}\n{bmi:.2f}', ha='center', va='bottom', fontsize=8)
        
         # Customize the chart with title, labels, gridlines, and legend
         plt.title('BMI Trend Over Time')
         plt.xlabel('Date')
         plt.ylabel('BMI Value')
         plt.ylim(0, max(bmi_values) + 5) # Automatically adjusts boundary <[ChatGPT]
         plt.xticks(bar_positions, dates, rotation=0)  # Rotate date labels for better readability
         plt.grid(True, axis='y', linestyle='--', alpha=0.7)  # Add gridlines for clarity
         plt.legend()
         # [ChatGPT] ^
         plt.show() # Display the generated bar graph
 
         # Print a detailed BMI tracking summary including date, weight, BMI, and classification
         print("BMI Tracking Summary Graph:")
         for date, weight, bmi, classification in zip(dates, weights, bmi_values, classifications):
             print(f"{date}: Weight = {weight} kg, BMI = {bmi:.2f}, Classification = {classification}")
     else:
         print("No data to display. You haven't calculated your BMI yet.")
        
    
   elif option == "4": #allows user to edit and see their personal profile
    new_gender = ''
    new_age = ''    
    while True:
     #displays the Profile menu until the user chooses CONFIRM
     print("""
     Press A to display your current profile.
     Press B to update your gender.
     Press C to update your age.
     Press R to go back.
     Enter CONFIRM to save changes
     """)
     update_option = input("Enter your choice: ").upper()
     if (update_option == "A"):
      # retrieves the user's info from the Records table
      cur.execute("""
      SELECT age, gender, height, weight FROM bmiHelper_RECORDS 
      WHERE user_id = ?
      ORDER BY date DESC
      LIMIT 1
      """, (userID,))
      result = cur.fetchone()
      age, gender, height, weight = result
      print("User ID: " + str(userID))
      print("Username: " + current_user)
      print("Age: " + str(age))
      print("Gender: " + gender)
      print("Height: " + str(height) + ' cm')
      print("Weight: " + str(weight) + ' kg')
     
     elif (update_option == "B"):
      #menu for updating gender 
      while True:
       g_option = input("""
       How do you identify?
             
       M - Male
       F - Female
       X - Gender non-conforming
       
       """)
       gender = ""
       if g_option == "M":
        new_gender = "Male"
        break
       elif g_option == "F":
        new_gender = "Female"
        break
       elif g_option == "X":
        new_gender = "Gender non-conforming"
        break
       else:
        print("Invalid input, please try again")
        continue
       
     elif(update_option == "C"):
      # enter new age
      new_age = input("Enter your new age: ")
      
     elif update_option == "R":
      # Exit the update loop if the user chooses to go back
      break
     
     elif (update_option == "CONFIRM"):
      # if changes were made, update profile
      if new_age != '' or new_gender != '':
       cur.execute("""
       UPDATE bmiHelper_RECORDS
       SET age = ?, gender = ?
       """, (new_age, new_gender))
       connect_db.commit()
       print("Changes saved successfully!")
       
      else:
       # if no changes were made, notify user
       print("No changes were made.")
      break
     else:
      print("Invalid input, please try again")
      continue
      
     

   elif option == "3": # GENERATE MEAL PLAN BASED ON LAST CALCULATED BMI
    # Retrieves user's age, weight, height, and gender (most recent entry)
    cur.execute("""
    SELECT age, weight, height, gender FROM bmiHelper_RECORDS
    WHERE user_id = ?
    ORDER BY date DESC
    LIMIT 1
    """, (userID,))
    result = cur.fetchone()
    user_age, weight_input, height_input, gender = result
    
    #Personal code
    #the function that prompts the user for the options to curate thier diet to their tastes
    def meal_plan(prompt, options):
        """
        INPUT: REQUIRED VALUES TO DETERMINE MEAL PLAN (Body Goals, Dietary preferences, 
        Activity level, Gender, Desired meals a day)
        
        OUTPUT: The given values. The values are stored to determine the meal plan for the user.
        All inputs must be valid to proceed and calculate BMR and PAL. It is expected 
        that the user has an account which stores their height and weight beforehand.
        """
        # [ChatGPT] v
        #used to diplay the menu
        while True:
            print(prompt)
            for key, description in options.items():
                print(f"{key}: {description}")
            choice = input("").strip().upper()
            if choice in options:
                return choice
            else:
                print("Invalid option. Please try again.\n")
        # [ChatGPT] ^
    
    # Personal code            
    body_goals_prompt = "Choose your desired goal:"
    body_goals_options = {
        "A": "Weight Gain",
        "B": "Weight Loss",
        "C": "Weight Maintenance"
    }
    
    diet_menu_prompt = "Choose a dietary path:"
    diet_menu_options = {
        "A": "Vegan",
        "B": "Vegetarian",
        "C": "Pescatarian",
        "D": "Anything"
    }
    
    meals_menu_prompt = "How many meals per day would you like? :"
    meals_menu_options = {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6"
    }
    
    activity_menu_prompt = "How active are you?"
    activity_menu_options = {
        "A": "Light - Daily activities",
        "B": "Moderate - Exercise periodically",
        "C": "Heavy - Exercise frequently"
    }
    
    # Collect user input using the menus
    first_choice = meal_plan(body_goals_prompt, body_goals_options)
    second_choice = meal_plan(diet_menu_prompt, diet_menu_options)
    third_choice = meal_plan(meals_menu_prompt, meals_menu_options)
    fourth_choice = meal_plan(activity_menu_prompt, activity_menu_options)
    
    # [ChatGPT] v
    # Map diet and meal choices to specific outputs
    diet_mapping = {
        "A": "Vegan",
        "B": "Vegetarian",
        "C": "Pescatarian",
        "D": "Anything"
    }
    
    meal_mapping = {
        "1": "1 meal",
        "2": "2 meals",
        "3": "3 meals",
        "4": "4 meals",
        "5": "5 meals",
        "6": "6 meals"
    }
    
    # Combine second and third choices for a specific result
    diet_result = diet_mapping[second_choice]
    meal_result = meal_mapping[third_choice]
    # [ChatGPT] ^
    
    #personal code
    # Display the final choices with full descriptions
    print("\nYour Input:")
    print(f"Body Goals: {body_goals_options[first_choice]}")
    print(f"Diet Option: {diet_menu_options[second_choice]}")
    print(f"Meals Per Day: {meals_menu_options[third_choice]}")
    print(f"Activity Level: {activity_menu_options[fourth_choice]}")
    
    #Calculate calorie intake
    # to input their activity level you must multiply by the corresponding PAL
    
    #personal code
    
    PAL = 0
    #calculates the ideal calorie count based on the excercise levels of the user 
    #PAL is a variable that is used to match a persons excerise levels. the higher amount 
    #of excersice an individual does, the more calories they burn, hence the PAL number is meant
    #to reflect that by having the caloric intake of a person increase based on how much excerise they do
    #since you burn more as you excise more, they will need to replace more to allow for daily function
    
    if activity_menu_options[fourth_choice] == "Light - Daily activities":
        PAL += 1.375
    elif activity_menu_options[fourth_choice] == "Moderate - Exercise periodically":
        PAL += 1.55
    elif activity_menu_options[fourth_choice] == "Heavy - Exercise frequently":
        PAL += 1.8
    
     #calculations used to detemine a persons required calorie intake minimum based on their age, height and weight
     # is then multiplied by theri pal value to take into account the calorie they burn based on their lifestyle
     
    calorie_men = int(88.4 + (13.4) * (int(weight_input)) + (4.8) * (int(height_input)) - (5.68) *(int(user_age))) * PAL
    calorie_women = int(447.6 + (9.25) * (int(weight_input)) + (3.10) * (int(height_input)) - (4.33) *(int(user_age))) * PAL
    calorie_n_g_c = int(calorie_men + calorie_women)/2
    
    #this is to account for diet goals. if the user wants to gain weight they must increase the required amount of calories
    #consumed per day, so that the excess caloire consumption can result in weight gain
    #the opposite applies for weight loss. if the user want to loos weight, they must be consuming less calories
    #than they need for daily function, which then results in weight loss 
     
    if (body_goals_options[first_choice] == "Weight Gain"):
        calorie_m = calorie_men *1.18
        calorie_w = calorie_women *1.18
        calorie_n = calorie_n_g_c *1.18
    elif (body_goals_options[first_choice] == "Weight Loss"):
        calorie_m = calorie_men *0.79
        calorie_w = calorie_women *0.79
        calorie_n = calorie_n_g_c *0.79
    else:
        calorie_m = calorie_men 
        calorie_w = calorie_women 
        calorie_n = calorie_n_g_c   
    
    
    # this is intended to tell the user about the amount of calories they should be consuming based on all the data they had inputed 
    #as well as the average for their gender identity
    if (gender == "Female"):
        print("The average Woman needs about 1600 to 2400 calories a day" + " you require about " + str(round(calorie_w)) + " calories")
        calorie = calorie_w
    elif (gender == "Male"):
        print("The average man needs about 2000 to 3000 calories a day" + " you require about " + str(round(calorie_m)) + " calories")
        calorie = calorie_m 
    elif (gender == "Gender non-conforming"):
        print("Other gender identities can vary in the amount of calories needed, so an average of both men and women is taken\n" + " you require about " + str(round(calorie_n)) + " calories")
        calorie = calorie_n
        
    #printed diet type to let the user know
    print(f"\nYour selected combination is: {diet_result} and {meal_result}")
    
    #[CHATGPT] v
    import random
    #function to read the txt file based on the diet type
    def read_random_items_from_column(diet_file, calorie_range, num_items):
        """
        Reads a given number of random items from a specified column in a text file.
    
        Parameters:
            diet_file (str): The path to the text file.
            calorie_range (str): The calorie range to filter values.
            num_items (int): The number of random items to select.
    
        Returns:
            list: A list of randomly selected items from the column.
        """
        try:
            # Open the file manually
            file = open(diet_file, "r")
            lines = file.readlines()
    
            column_values = []
            start_collecting = False
    
            # Parse lines to find the calorie range section
            for line in lines:
                line = line.strip()
                if line.startswith(calorie_range):  # Found the calorie range, start collecting
                    start_collecting = True
                elif start_collecting and line == "":  # Stop when an empty line is found
                    break
                elif start_collecting:
                    column_values.append(line)
    
            file.close()
    
            # Check if there are enough values in the column to select from
            if len(column_values) < num_items:
                print(f"Error: Not enough values in the column to select {num_items} items.")
                return []
    
            # Randomly select the requested number of items
            random_items = random.sample(column_values, num_items)
            return random_items
    #error pathway
        except FileNotFoundError:
            print(f"Error: The file {diet_file} was not found.")
            return []
    
    #display the user decisions
    def display_meals(diet_file, calorie_range, num_items):
        """
        Displays a random selection of meals and allows the user to regenerate if desired.
        """
        while True:
            random_items = read_random_items_from_column(diet_file, calorie_range, num_items)
            if random_items:
                print("\nHere are some meals to try:")
                for item in random_items:
                    print(f"- {item}")
    
                regenerate = input("\nDon't like these options? Enter 'Y' to generate new meals or any other key to exit: ").strip().lower()
                if regenerate != 'y':
                    break
            else:
                print("No valid meals found. Exiting.")
                break
    
    
    selected_file = diet_menu_options[second_choice]
    # [CHATGPT] ^
    
    diet_file = f"{selected_file}.txt"
    #personal code
    if 0 <= calorie <= 1600:
        calorie_range = "0-1600 Calories (Low-Calorie Recipes):"  #Replace with your desired column name
        #change so the resulting calorie will print a specific section within a txt file
        #make a randomizer to pick out the meals
    elif 1600 <= calorie <= 2600:  # Adjusted to avoid overlap with previous range
        calorie_range = "1600-2600 Calories (Everyday Recipes):" 
    else:
        calorie_range = "2600+ Calories (High-Calorie Recipes):" 
    num_items = int(meals_menu_options[third_choice])  # Replace with the number of items you want
    
    # Main logic to print results
    random_items = read_random_items_from_column(diet_file, calorie_range, num_items) # [CHATGPT]
    
    
    # Call the function to start the process
    display_meals(diet_file, calorie_range, num_items)
    
    #print meals according to how many they pick
    #txt files created by chatgpt        
     
   elif option == "RESET": # WIPES ALL DATA FROM USERS TABLE
        cur.execute("""
        DROP TABLE bmiHelper_USERS
        """)
        cur.execute("""
        DROP TABLE bmiHelper_RECORDS
        """)        
        connect_db.commit()
        print("Data wiped successfully")
        
   elif option == "X":
        # Exits program
        print("PROGRAM QUIT")
        
   else:
        print("Invalid input, please try again")
        continue
     
        
connect_db.close()